### ISSUE TITLE
Comments within yaml file of group members

### ISSUE THREAD

**Issue by lornat75** [icub-tech-iit/outside-collaborators#187]
### Is your feature request related to a problem?

No

### The solution you would like to have available

When I revise the list of github accounts to delete/add new ones for some of them I have a hard time remembering to whom they correspond to. If we could add the full name as a comment in the yaml file next to the nick name it would be nice.

### Alternatives you have considered

No

**Comment by pattacini** [comment]
This is a good point @lornat75 👍🏻 

YAML already handles comments as per https://www.tutorialspoint.com/yaml/yaml_comments.htm.
Given that the ruby script makes use of a full-fledged YAML library, we should be already good to go.

Let me run some tests locally.
Stay tuned.

**Comment by pattacini** [comment]
I've just tried out the following modifications:
```yml
hsp-iit/everyone:
  - "lornat75"
  - "randaz81"
  - "xEnVrE"
  - "Arya07" # Elisa
  - "GiuliaP"
  - "MariaLombardi"
  - "morpheus1820"
  - "elandini84"
  - "damianomal"
  - "fedeceola"
  # Stefano
  - "ste93"
  - "gabrielecaddeo"
  - "andreamaracani"
  - "FedericoVasile1"
  - "LZC-68"
  - "Woolfrey"
  - "steb6"
  - "andrearosasco"
  - "SimoneMic" 
  - "EnricoGhiorzi"
  - "fenixkz"
  - "vigisushrutha23"
  - "rozzong"
  - "CarmelaCalabrese" 
  - "fbrand-new" 
  - "colombraf"
  - "pestrstr"
  - "PasMarra"
```

and the script worked successfully.
So, I think @lornat75 you could now edit your group by inserting convenient comments.

**Comment by lornat75** [comment]
does it also work if it is on the same line? 
- "xynick" #Mr Ricky Rich

**Comment by pattacini** [comment]
Yep, the example above contains one instance of that:
```yml
  - "Arya07" # Elisa
```

**Comment by lornat75** [comment]
> Yep, the example above contains one instance of that:
> 
> ```yaml
>   - "Arya07" # Elisa
> ```

right I had missed it!
