### ISSUE TITLE
[mentioning] Do all repositories need access to the PAT of org admin?

### ISSUE THREAD

**Issue by JeroenKnoops** [icub-tech-iit/outside-collaborators#7]
In order to get the mentioning working, we need to create an organizational wide secret with the PAT with **org admin** rights.

This means that all outside collaborators have access to the PAT and can add a little workflow to display the token. This is already a problem for 'normal' users in an organization, but even more for outside collaborators.

I understand the PAT is needed for the outside-collaborators repository with the definations of the groups and outside collaborators. With protected branches this is also no problem. 

# Question
Do the other repositories also need a PAT with **org admin** rights?

# Context
I'm working for Philips with >2000 developers...

**Comment by pattacini** [comment]
Hi @JeroenKnoops 

Thanks for pointing out this sort of vulnerability 👍🏻 
I could actually add it up to the [⚠ Known limitations/issues][1] section.

>Do the other repositories also need a PAT with org admin rights?
A PAT with full repo scope is needed for the mentioning mechanism of the automated repos. Non-automated repos do not need any PAT, although the PAT as I've formulated the framework is organization-wide.

One could circumvent this by:
- Creating local PAT for each automated repo, but I'm afraid that the user owning the PAT should remain an org admin. Thus, the vulnerability persists. A PAT should be required even if the script responsible for mentioning would be running locally to the repo as we still need to grab information from the central repo dashboard.
- Not using the mentioning mechanism but only the centralized managing of outside collaborators.

When GitHub will provide the possibility to trigger workflows with webhooks (see [FAQ][2]), we will be able to get rid of the specific local triggering workflow.

I haven't looked into trying to fix this vulnerability outright yet; I might be fiddling with this in the next days. However, if you have suggestions, please don't hesitate to show up!

Thanks again!

[1]: https://github.com/icub-tech-iit/outside-collaborators#-known-limitationsissues
[2]: https://github.com/icub-tech-iit/outside-collaborators/blob/master/FAQ.md

**Comment by pattacini** [comment]
Another possibility to get around the PAT would  be designing an equivalent GitHub APP, I suppose.

**Comment by JeroenKnoops** [comment]
Indeed, that would be a good approach.

I will try to get it working in our GitHub App / Lambda setup. ( https://github.com/philips-labs/terraform-aws-github-runner )
If I get it to work, I will create a similar PR here.

**Comment by pattacini** [comment]
Actually I have no experience with GitHub Apps, so that would really help out.

**Comment by pattacini** [comment]
@JeroenKnoops with a second thought I could do the following: instead of propagating the information from the automated repos to the central dashboard, we can isolate the processing within the locally to the repositories thus without needing any PAT. As a result, we will still need a PAT for running the main scripts in the central dashboard but, in this case, the PAT is not required to be organization-wide. Access to the dashboard is granted only to org admins.
