### ISSUE TITLE
Github action still seems successful even if collaborators weren't added

### ISSUE THREAD

**Issue by renaissanceGeek** [icub-tech-iit/outside-collaborators#80]
### Bug description

If there are errors adding any users, such as a typo in the repo name, the github action still succeeds.  The error shows up with a helpful red X in the log message, but it's not obvious that the logs need to be checked since the job was successful.

In my case, the issue was that I had run out of seats in our paid plan, which also wasn't easy to figure out because the error message was just "problem detected".

### Steps to reproduce

1. Create a new file under `repos` called `dummy.yml` (assuming there isn't a repo called `dummy`!)
```
dummy:
  some-group:
    type: "group"
    permissions: "read"
```
2. Run the "Update Outside Collaborators" job
3. Job will complete successfully, even though there are errors in the log

### Expected behavior

I'd expect the job would fail and the logs would have enough details to diagnose

### Additional context

I have a simple fix that I can contribute back, but I'm not a Ruby developer, so it might not be idiomatic.

**Comment by pattacini** [comment]
Thanks heaps @renaissanceGeek for reporting on this! I'm happy to see that you used the automation ✨

Yours is actually a very good point. I'm on your linked PR.
