### ISSUE TITLE
Rate limit exception got at a safeguarded seemingly single operation

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/outside-collaborators#86]
>I get a rate limit exception at
>
>```
>	from ./outside-collaborators-handler.rb:69:in `add_repo_collaborator'
>```
>
>Strange, there is a `check_and_wait_until_reset` just before that line..

_Originally posted by @JeroenKnoops in https://github.com/icub-tech-iit/outside-collaborators/issues/78#issuecomment-933188356_

**Comment by pattacini** [comment]
Here's the line:

https://github.com/icub-tech-iit/outside-collaborators/blob/0f7fa4be91da0a66b84e5a571a0c1dbb14a4335d/scripts/outside-collaborators-handler.rb#L69

**Comment by pattacini** [comment]
Hi @JeroenKnoops 

This bug is a bit puzzling.
The documentation doesn't provide any useful clue as to if the operation shouldn't be considered single/atomic for any reason:
- http://octokit.github.io/octokit.rb/Octokit/Client/Organizations.html#organization_member%3F-instance_method
- https://docs.github.com/en/rest/reference/orgs#check-organization-membership-for-a-user

You may try to give the safeguard on the rate limit a bit of slack by relaxing the following condition

https://github.com/icub-tech-iit/outside-collaborators/blob/0f7fa4be91da0a66b84e5a571a0c1dbb14a4335d/scripts/helpers.rb#L8

into something like

```ruby
if rate_limit.remaining >= 10 then 
```

It's a mere workaround I know but it would help us inquire the problem a bit deeper.

**Comment by pattacini** [comment]
Hi @JeroenKnoops 

Did you get this error again while running your jobs?

**Comment by JeroenKnoops** [comment]
I've changed the line in the `helpers.rb` to already wait when rate_limit is < or equal to two and that resolved it.
<img width="1204" alt="Screenshot 2021-11-15 at 13 52 22" src="https://user-images.githubusercontent.com/10019/141785270-ba0747cd-addb-412e-b4a6-1dc8f49128a2.png">

**Comment by pattacini** [comment]
Fantastic!
I'll open up a PR then.
