### ISSUE TITLE
Mentioning Breaking - Need Info

### ISSUE THREAD

**Issue by dhruvg20** [icub-tech-iit/outside-collaborators#9]
Hi:

Pretty helpful tool and thank you for building it. 

When I try the mentioning logic, it breaks with appending msg. 
I have made the management Repo/Dashboard as Public and added the Action Workflow file in the accessing Repo. 
Please let me know if anything I am missing? 

![image](https://user-images.githubusercontent.com/20143038/96970450-57781380-1531-11eb-953c-d27cc4e4e1b7.png)

**Comment by dhruvg20** [comment]
A Challenge I see why we need to make the Repo Public, which would hinder adoptions for larger companies.

**Comment by pattacini** [comment]
> Pretty helpful tool and thank you for building it.

Thanks @dhruvg20 👍🏻 

As you can see from the log, the repo `https://github.com/outside-collaborators/outside-collaborators.git` does not exist. Indeed, you renamed the main repo as https://github.com/outside-collaborators/outside-collaborators-dashboard in your brand new organization.

Therefore, you'd better check the codebase to update here and there all the references. For this particular case, you ought to update this [line of the template](https://github.com/icub-tech-iit/outside-collaborators/blob/master/templates/.github/workflows/create-mentioning-comment.yml#L32) plus of course the action you deployed in your private repos.

>A Challenge I see why we need to make the Repo Public, which would hinder adoptions for larger companies.

This is a more complicated story.

The requirement of having the repo public is just for the mentioning mechanism as stated in the README. Being public, the main dashboard can be freely downloaded from any other private repo of the same org without needing to set up a Private Access Token (PAT), which can turn out to be a vulnerability.

To circumvent this, one could create a GitHub App, which I won't do, at least for now, for the reasons explained in [`FAQ`](../blob/master/FAQ.md).

See for references: #7, #8.

**Comment by dhruvg20** [comment]
Hi @pattacini thank you for sharing the logic, and it is working now. 

My aim to make the `outside-collaborators/outside-collaborators` private, I made a change in the Workflow logic to download the Private Repository: `outside-collaborators/outside-collaborators`, by raising the PAT `OUTSIDE_COLLABORATORS_TOKEN_BOT` to the Organization level secrete and used the action/checkout, as seen below. 
It started to work too. 🙇  thanks. 

![image](https://user-images.githubusercontent.com/20143038/96996818-2954fc80-154e-11eb-9ed2-7e1e6ae3c7e3.png)


``
    steps:

      - name: Install Dependencies
        run: |
          sudo gem install octokit yaml

      - name: Checkout Private Repository
        uses: actions/checkout@v2
        with:
          path: outside-collaborators
          repository: outside-collaborators/outside-collaborators
          token: ${{ secrets.OUTSIDE_COLLABORATORS_TOKEN_BOT }} 
            
      - name: Set Env Variables
        run: |
          echo "OUTSIDE_COLLABORATORS_GITHUB_REPO=${{ github.repository }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_EVENT_NAME=${{ github.event_name }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_ISSUE_NUMBER=${{ github.event.issue.number }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_PR_NUMBER=${{ github.event.pull_request.number }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_COMMENT_ID=${{ github.event.comment.id }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> ${GITHUB_ENV}
      - name: Run Handler
        run: |
          cd ./outside-collaborators/scripts
          ./mentioning-comment-handler.rb
``

**Comment by pattacini** [comment]
In the recent past, I was also relying on an organization-level PAT, but this represents a vulnerability as non-admin users with write access to your private repo could possibly run actions accessing that PAT and thus retrieving sensitive information of the organization.

**Comment by dhruvg20** [comment]
The above makes sense, the challenge of making Repo Public and accessible to the world is much larger and anyone can make a change. I guess it is a trade-off, there no full-proof secure set up at all.

**Comment by pattacini** [comment]
Yes, for us disclosing the visibility of the collaborators' structure is not a big concern, but be careful as with your approach even an external collaborator with `write` permission could be granted access to the whole org.

Instead, if you deem to deal with `read` and/or `triage` permissions only you're good to go.

**Comment by dhruvg20** [comment]
Thank you, @pattacini, for discussing the above. I was also trying out [Add Files to many Repositories on your Org](https://github.com/code-dhruvg20/org-repos-files-setup), as the workflow files can be added to many Repositories of an Organization.

**Comment by pattacini** [comment]
Nice resource indeed, thanks for pointing it out 👍🏻
